### ISSUE TITLE
Speed Control

### ISSUE THREAD

**Issue by gitrago** [zhw2590582/SubPlayer#10]
this is awesome work! Thank you! I only have one question: is there a trivial way to add playback speed control to the video display element?

**Comment by zhw2590582** [comment]
There is already a right-click menu to control the video speed, If you want to be more intuitive, you can add settings panel or bottom menu.

[demo](https://artplayer.org/?libs=&code=var%20url%20%3D%20%27https%3A%2F%2Fzhw2590582.github.io%2Fassets-cdn%27%3B%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20url%20%2B%20%27%2Fvideo%2Fone-more-time-one-more-chance-480p.mp4%27%2C%0A%20%20%20%20playbackRate%3A%20true%2C%0A%20%20%20%20setting%3A%20true%2C%0A%20%20%20%20autoSize%3A%20true%2C%0A%20%20%20%20controls%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20position%3A%20%27right%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%271X%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20click%3A%20function()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20art.playbackRate%20%3D%200.5%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20position%3A%20%27right%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%272X%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20click%3A%20function()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20art.playbackRate%20%3D%202%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%7D)%3B)
