### ISSUE TITLE
请问如何修改字幕样式

### ISSUE THREAD

**Issue by TroTreboRn** [zhw2590582/SubPlayer#11]
想要自写一个字幕样式的动态配置，参考artplayer的文档在subtitle: { style: {'font-size': '28px'}} 生效了, 但是当我更改配置时 player.js接受到了参数但是实际style没有改变。

**Comment by zhw2590582** [comment]
artplayer的配置里本身不支持动态修改字幕样式的，但很容易直接修改，实例的`art.template.$subtitle`就是字幕的dom元素，直接修改就可以了。

```js
art.template.$subtitle.style.color = '#fff';
```

**Comment by TroTreboRn** [comment]
thx
