### ISSUE TITLE
making changes to the example demo

### ISSUE THREAD

**Issue by ahmad-ali14** [zhw2590582/SubPlayer#14]
making any changes to the example demo should not be saved and if I refresh the page, the example demo should go again to its initial state

![](https://i.imgur.com/tO1mYvo.png)

**Comment by zhw2590582** [comment]
The subtitle data is saved locally to prevent data loss. It's like you spent a long time editing subtitles but accidentally closed the browser. If you want to clear the subtitles, you can click the Clear button at the top
