### ISSUE TITLE
Issue opening  video

### ISSUE THREAD

**Issue by indulanka** [zhw2590582/SubPlayer#17]
Dear Harvey,
There is an issue with opening some videos with the open option.

Please be kind enough to send me the code to fix this issue.
I have attached the screenshot of the issue.
![video_error](https://user-images.githubusercontent.com/63869311/82048741-ccb60180-96d2-11ea-9e30-54301334849c.png)

Kind regards,
Indunil Sanjeewa

**Comment by zhw2590582** [comment]
You only need to comment out or delete the error code

https://github.com/zhw2590582/SubPlayer/blob/66d133dbced5847066990839df5b9ebcaf546f6c/src/waveform/decoder.js#L31

**Comment by ahmad-ali14** [comment]
you can also click on the `x` close button, the app is not crashed
