### ISSUE TITLE
看了这个字幕工具非常佩服作者的功力

### ISSUE THREAD

**Issue by lixingyangok** [zhw2590582/SubPlayer#19]
另外想请问有在安装时遇到下列报错吗， 我这安装了几次没安成功
No matching version found for react-i18nify@^3.1.6

后来吧  package.json 里面的相关依赖改成了   "react-i18nify": "^3.0.0", 安上了

**Comment by zhw2590582** [comment]
多谢，但react-i18nify目前最新npm版本就是3.1.6，无法复现你所描述的问题
