### ISSUE TITLE
allow to modify the time manually, auto tile the nearest time

### ISSUE THREAD

**Issue by xhebox** [zhw2590582/SubPlayer#20]
**EDIT**: I found #16 mentioned editable time boxes, then this issue only posts the idea of automatically tiling.

If I did not miss anything, then the only ways to modify the time are dragging and offset buttons.

It is good to make time editable, because sometimes it is impossible to put one subtitle next to the previous one, just by one unit time. Or put it exactly on the right time just by dragging.

It will be even better that if the current subtitle, when modifying the range of time or moving, can automatically(magnetically) tile to the nearest timeline, or other subtitles. That would be a huge improvement on user interface and productivity.

**Comment by zhw2590582** [comment]
Your idea of ​​automatic alignment is very good, I will add it in the next version, thank you for your feedback

**Comment by zhw2590582** [comment]
Fixed!
