### ISSUE TITLE
long subtitles are not displayed

### ISSUE THREAD

**Issue by xhebox** [zhw2590582/SubPlayer#21]
A long subtitles that crossed a whole section over the timeline will not be displayed:

```
timeline ->
block1 | block2 | block3
   |------longsub-----|
```

It will display in block1 and block3 normally, but not block2.

**Comment by zhw2590582** [comment]
I don't quite understand the problem you describe. Can you paste your subtitle text?

**Comment by xhebox** [comment]
Say my subtitle is `xxx` from 5.635s to 25.545s. The bottom timeline starts from 0s to 10s(block1), 10s to 20s(block2), 20s to 30s(block3).

Then you can see the subtitle in block1, block3, but not block12. I mean you can see that blue, selected, subtitle rectangle at the bottom with `xxx` texts in block1 and block3. But you can not see anything in block2. No rectangle, no texts... Nothing.

As if there is no subtitle from 10s to 20s. But there is one: the `xxx` subtitle from 5s to 25s. This subtitle is too long that it is even longer than a timeline block. This should be a corner case.

These two images will clarify the problem:

https://img.vim-cn.com/2f/a233d7b3e275df00f615a7ea0e06fce1c396ed.png 
https://img.vim-cn.com/e9/53faefcee2be66397132ae00d7795fd5d7e01f.png

**Comment by zhw2590582** [comment]
I understand what you mean, it is a bug, I will fix it in the next version, thank you for your feedback

**Comment by zhw2590582** [comment]
Fixed!
