### ISSUE TITLE
EPERM Error

### ISSUE THREAD

**Issue by indulanka** [zhw2590582/SubPlayer#22]
Hi Harvey,

I get an error when minimizing or exiting browser and executing the npm run build command again in the visual studio code terminal.

Kind regards,
Indunil Sanjeewa

![problem](https://user-images.githubusercontent.com/63869311/85111365-daaaf500-b231-11ea-921a-f839272780f1.png)

**Comment by zhw2590582** [comment]
https://stackoverflow.com/questions/34600932/npm-eperm-operation-not-permitted-on-windows
