### ISSUE TITLE
Ran out of memory

### ISSUE THREAD

**Issue by Yuzi1221** [zhw2590582/SubPlayer#27]
page keeps crashing when playing a video that is 110mb...

**Comment by Yuzi1221** [comment]
I'm so sad I was really hoping to translate this anime for my boyfriend to chinese so he could read it... and everything I try doesn't work... tried many ways... this was my last hope of manually translating...

**Comment by Yuzi1221** [comment]
I read that its not suitable for opening large files... sorry for opening this issue...

**Comment by Yuzi1221** [comment]
unless there's a way to open large files with a certain browser or something... Im using Opera GX with max settings...

**Comment by ForTheSakuya** [comment]
You can download this Code ,then find the code "this.loader.load" in the path "src/waveform/index.js"  and delete this row.
save to run
