### ISSUE TITLE
What does it mean ?

### ISSUE THREAD

**Issue by andrewBIsP** [zhw2590582/SubPlayer#28]
_docs/index.html_

```javascript
function() {
    if (!isLocalhost) {
        var o = document.createElement("script");
        o.src = "https://hm.baidu.com/hm.js?9c948099957cd6a524dac835394d4495";
        var t = document.getElementsByTagName("script")[0];
        t.parentNode.insertBefore(o, t)
    }
}()
```

**Comment by zhw2590582** [comment]
Similar to Google statistics script, but it comes from Baidu

**Comment by andrewBIsP** [comment]
it's not good practice, i suppose

**Comment by zhw2590582** [comment]
I don't understand. It's just used to count website visits

**Comment by andrewBIsP** [comment]
for whom ?

**Comment by zhw2590582** [comment]
For me and my website(subplayer.js.org)

**Comment by andrewBIsP** [comment]
It's obvious, but why do people need your baidu analytics script ?

**Comment by zhw2590582** [comment]
This project is not released as a dependency, I initially thought it would be published as my personal website. People have enough flexibility to modify all the code. I didn't add a more friendly hint to the script that people can delete these lines of code. It's really my fault.
