### ISSUE TITLE
提一个波形不正确的问题

### ISSUE THREAD

**Issue by lixingyangok** [zhw2590582/SubPlayer#31]
**zhw2590582** 您好：
我发现了 https://subplayer.js.org 一个小bug。
即某些【特定的音频】波形会有不正确的情况，描述如下。

具体表现为：
● 比如在第 10 秒处存在波形（波峰），但声音是延后了2秒才出现的。
● 换个说法：在 12 秒处播出了声音，但在之前第 10 秒处就出现了波形。
● 由此导致声音和波形无法对应，
如图

然后我做了一个考证：
● 用其它几个工具校验了一下波形的正确性（见下图），发现字幕和音频在其它软件中能正常对应。只在我们 subplayer 正确不能对应，即上文提到的声音比波形慢半拍。
● 怀疑音频有特殊性，用软件工具做了格式转换（如 ffmpeg.js 和格式工厂） 比如把它转为 aac, ogg, mp3 然后把转换之后的文件导入 subplayer 后波形和字幕就对应了。

▼图
![Snipaste_2021-02-20_19-05-07](https://user-images.githubusercontent.com/19503772/108593720-5a382780-73b0-11eb-9940-865f30ba2cc7.jpg)

▼音频
[新概念.zip](https://github.com/zhw2590582/SubPlayer/files/6014833/default.zip)

**Comment by zhw2590582** [comment]
是的，我开始做的时候也发现这个问题，网页版使用的是`AudioContext`生成的PCM音频数据，和`ffmpeg`生成的PCM音频数据有一定差别，目前还没研究怎么纠正

**Comment by lixingyangok** [comment]
> 是的，我开始做的时候也发现这个问题，网页版使用的是`AudioContext`生成的PCM音频数据，和`ffmpeg`生成的PCM音频数据有一定差别，目前还没研究怎么纠正

哦哦。好，我探索一下，将来有啥进展再至此留下消息。
感谢回复 ❤
