### ISSUE TITLE
DOMException: Unable to decode audio data

### ISSUE THREAD

**Issue by qingwufong** [zhw2590582/SubPlayer#32]
Hi, I use artplayer to play a m3u8 list, that is ok. but waveform cannot be create on the bottom of the page. It gived a error that: "Uncaught (in promise) DOMException: Unable to decode audio data". It there some solution about that？I think it may not was a issule of subplayer. Wish you reply， thank you！
![error-img](https://user-images.githubusercontent.com/6860888/109767433-85cdd400-7c32-11eb-8042-02122e1f6184.png)

**Comment by zhw2590582** [comment]
波形图的原理是解码出音频的PCM数据，subplayer的这个功能由web api的`AudioContext`来实现的，这个并不支持解码所有流媒体数据，如m3u8

**Comment by qingwufong** [comment]
> 波形图的原理是解码出音频的PCM数据，subplayer的这个功能由web api的`AudioContext`来实现的，这个并不支持解码所有流媒体数据，如m3u8

感谢解答，我再想想别的办法
