### ISSUE TITLE
Facing problem in creating metronome

### ISSUE THREAD

**Issue by salmanAhmad143** [zhw2590582/SubPlayer#33]
Hey @zhw2590582,

Please help me to solve an issue. I have implemented the same code in my editor but my problem is that metronome is not placing at the same place of pointer when i start dragging the mouse. Actually i am unable to find the mouse clicked position in timeline. Could you please explain the logic behind this?

I saw a function called getEventTime in metronome.js. Only this is using to get the mouse click location or any where else?

Please explain how you are calculating the mouse clicked position in detail.

`const getEventTime = useCallback(

        event => {
            return (event.pageX - render.padding * gridGap) / gridGap / 10 + render.beginTime;
        },
        [gridGap, render],
    );`

Please tell me how it's converted into pixel from time here?

`<div
      className="templet"
      style={{
          **left: render.padding * gridGap + (drogStartTime - render.beginTime) * gridGap * 10,
          width: (drogEndTime - drogStartTime) * gridGap * 10,**
      }}
  >
</div>`

Thanks,

**Comment by zhw2590582** [comment]
![1](https://user-images.githubusercontent.com/5907357/113108923-14387400-9238-11eb-97e2-e86af564761e.png)

event.pageX: Represents the location of the current mouse.
gridGap: Represents the space interval of every 0.1 second, in pixels
gridGap * 10: Represents the distance per second
render.beginTime: Represents the start time of the current canvas
render.padding * gridGap: It's the blank area on the left. Here's the render.padding It's five

```js
(event.pageX - render.padding * gridGap) / (gridGap * 10) + render.beginTime
```

**Comment by zhw2590582** [comment]
110 is the initial value, 5 on the left, 5 on the right, and 100 in the middle
