### ISSUE TITLE
Problem update page

### ISSUE THREAD

**Issue by Angelk90** [zhw2590582/SubPlayer#39]
Hi @zhw2590582 , 
it happens that when I load a video and subtitles and then reload the page the subtitles remain, but the video doesn't.

1) I upload the video
2) I upload the subtitles
3) I update page F5
4) The video I uploaded does not appear, in its place the default one (I think normal behavior).
But the subtitles those uploaded by me remain, but not the default ones.

**Comment by zhw2590582** [comment]
Because this is to prevent accidental loss of subtitles, I have saved the subtitles in the local cache, but the video is too big so I don’t want to save it to the cache.

**Comment by Angelk90** [comment]
@zhw2590582 : OK! I got it.
