### ISSUE TITLE
backlight.js:27 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.

### ISSUE THREAD

**Issue by Angelk90** [zhw2590582/SubPlayer#40]
Hi @zhw2590582 ,
I noticed this thing, that when I open the console of the errors in the dimensions that are seen in the video the following problem occurs.

It's not very important, but I think it's a page size issue.

https://user-images.githubusercontent.com/20476002/118248582-bfc61c80-b4a4-11eb-9c3b-cc896eff9a8e.mov

P.s.
Is the online.aimu-app.com project always yours?
Because I noticed a problem.

**Comment by zhw2590582** [comment]
Yes, I know this, but it is not important and can be ignored

**Comment by Angelk90** [comment]
@zhw2590582 : 
The problem seems to be here:
https://github.com/zhw2590582/SubPlayer/blob/b2f71e1d7d6f96e09c49e5d073fec78c7c18f917/src/libs/backlight.js#L27

One way I've found not to have this problem is to do something like this:

```javascript
if(itemW < 1 || itemH < 1)  return { r: 0, g: 0, b: 0 };
const { data } = ctx.getImageData(itemX, itemY, itemW, itemH);
```

**Comment by zhw2590582** [comment]
Thank you. It has been updated
