### ISSUE TITLE
希望能支持导出 srt、ass格式的字幕

### ISSUE THREAD

**Issue by QuentinHsu** [zhw2590582/SubPlayer#5]
如题。
因为有时候，仅需要调整字幕文件的内容（保留当前的字幕文件格式（srt、ass））。
感谢大佬们的付出！

**Comment by zhw2590582** [comment]
可以是可以，但目前还不想复杂化，毕竟vtt转srt、ass也有很多在线工具可以做到了，将来重构的话可以加入这个。

**Comment by QuentinHsu** [comment]
好的 感谢。向大佬学习！
