### ISSUE TITLE
是否考虑加入快捷键功能

### ISSUE THREAD

**Issue by LuRenJiasWorld** [zhw2590582/SubPlayer#6]
如题所示。好用的快捷键系统对于做字幕的效率有很大提升，熟练之后几乎不用鼠标就可以完成字幕制作。请问可以在将来的版本加入这一功能吗？

**Comment by zhw2590582** [comment]
可以有，重构的时候会加上快捷键。

**Comment by DarkKris** [comment]
捕捉到路人甲

> 如题所示。好用的快捷键系统对于做字幕的效率有很大提升，熟练之后几乎不用鼠标就可以完成字幕制作。请问可以在将来的版本加入这一功能吗？

**Comment by zhw2590582** [comment]
已经重构
