### ISSUE TITLE
window.crossOriginIsolated

### ISSUE THREAD

**Issue by karanjakhar** [zhw2590582/SubPlayer#69]
Video loading and export works fine at localhost ( during development locally) but when I deploy it on AWS then through deployed link it give "Decoding audio failed" and also doesn't show video export option. 
Please help me.

**Comment by karanjakhar** [comment]
Solved. If anybody else is facing this. Please add below to your headers: 
 'Cross-Origin-Embedder-Policy': 'require-corp'
 'Cross-Origin-Opener-Policy': 'same-origin'

**Comment by bumpingbell** [comment]
Excuse me, I've noticed that this project's dependencies have been broken for some time. In this situation, could you please share how you managed to set up and run the project? I'd appreciate hearing back from you.
